"""Reference implementations for library procedures no source in a build defines.

``use lapack, only: dgesv, dgbsv`` names a module whose whole content is
interface blocks: the declarations are real -- they are what the compiler
checked the call against -- and the bodies are in a library the original
program linked. A build staged from the tree links no such library, and that
costs more than a missing symbol. The reference build cannot define ``dgesv``,
so ``undefined_externals`` gives it a body that refuses and ``reaching`` marks
every subprogram that would arrive there as one the differential holds no
reference for; the translation, meanwhile, spells the call ``_lapack.dgesv(...)``
into a module that defines nothing of the name. ``spline3`` and ``spline3pars``
came out of that with a passing unit and nothing compared.

What is supplied here is the third answer: for the few procedures whose
contract is small enough to state exactly, one implementation written twice --
once as the Fortran the reference build compiles, once as the Python the
translation calls -- statement for statement, so the two sides stand in for the
missing library the *same* way and round alike. The differential then compares
the translation of everything around the call, which is the part recast wrote,
instead of declining to compare it at all.

Two things this is not, and both are said on the verdict (``substituted``):

* It is not LAPACK. It is straightforward Gaussian elimination with partial
  pivoting, so it answers the same question to within its own rounding, and a
  build that links the real library will not reproduce these bits. A gate that
  ran against this stood in for the library on both sides and says so.
* It is not a way to translate a library. Anything beyond ``SUPPORTED`` is
  still declared, still undefined, and still disclaims its callers -- an
  audited ``externals`` shim is what covers those, and it is the operator's to
  supply.

The pairs are kept in one file, next to each other, because the only thing that
makes them useful is that they agree; ``tests/test_references.py`` compiles the
Fortran and runs the Python over the same draws to hold them there.
"""

from __future__ import annotations

from collections.abc import Iterable

__all__ = ["SUPPORTED", "fortran_for", "python_for", "reason", "supported"]

SUPPORTED = frozenset({"dgbsv", "dgesv"})
"""Procedures this module can stand in for, by lower-case name."""

REASON = (
    "no source in this build defines it; recast's own reference implementation "
    "stands in for the library on both sides"
)

_FORTRAN_HEADER = """\
! Machine-generated by recast for the reference build.
! Reference implementations for procedures this build declares an INTERFACE
! for and defines nowhere. The same arithmetic, in the same order, is emitted
! into the translation, so both sides of the differential stand in for the
! library that is missing here in the same way.
"""

_FORTRAN_HELPER = """\
subroutine recast_ref_gepp(n, nrhs, a, lda, ipiv, b, ldb, info)
  ! Gaussian elimination with partial pivoting: factor A and solve A*X = B,
  ! both in place. The pivot search takes the first row of largest modulus,
  ! the elimination runs right-looking column by column, and the right-hand
  ! sides are carried along with it, so there is one traversal of the matrix
  ! and the Python beside this one can be read against it line by line.
  implicit none
  integer, intent(in) :: n, nrhs, lda, ldb
  integer, intent(out) :: ipiv(*), info
  double precision, intent(inout) :: a(lda,*), b(ldb,*)
  integer :: i, j, k, p
  double precision :: amax, t
  info = 0
  if (n < 0 .or. nrhs < 0 .or. lda < max(1, n) .or. ldb < max(1, n)) then
     info = -1
     return
  end if
  do k = 1, n
     p = k
     amax = abs(a(k,k))
     do i = k + 1, n
        if (abs(a(i,k)) > amax) then
           amax = abs(a(i,k))
           p = i
        end if
     end do
     ipiv(k) = p
     if (a(p,k) == 0.0d0) then
        info = k
        return
     end if
     if (p /= k) then
        do j = 1, n
           t = a(k,j)
           a(k,j) = a(p,j)
           a(p,j) = t
        end do
        do j = 1, nrhs
           t = b(k,j)
           b(k,j) = b(p,j)
           b(p,j) = t
        end do
     end if
     do i = k + 1, n
        a(i,k) = a(i,k) / a(k,k)
     end do
     do j = k + 1, n
        do i = k + 1, n
           a(i,j) = a(i,j) - a(i,k) * a(k,j)
        end do
     end do
     do j = 1, nrhs
        do i = k + 1, n
           b(i,j) = b(i,j) - a(i,k) * b(k,j)
        end do
     end do
  end do
  do j = 1, nrhs
     do i = n, 1, -1
        t = b(i,j)
        do k = i + 1, n
           t = t - a(i,k) * b(k,j)
        end do
        b(i,j) = t / a(i,i)
     end do
  end do
end subroutine recast_ref_gepp
"""

_FORTRAN = {
    "dgesv": """\
subroutine dgesv(n, nrhs, a, lda, ipiv, b, ldb, info)
  ! LAPACK's DGESV contract: A is overwritten by its factors, IPIV by the
  ! pivot rows, B by the solution, INFO by the column a zero pivot was found
  ! in (0 when there was none).
  implicit none
  integer, intent(in) :: n, nrhs, lda, ldb
  integer, intent(out) :: ipiv(*), info
  double precision, intent(inout) :: a(lda,*), b(ldb,*)
  call recast_ref_gepp(n, nrhs, a, lda, ipiv, b, ldb, info)
end subroutine dgesv
""",
    "dgbsv": """\
subroutine dgbsv(n, kl, ku, nrhs, ab, ldab, ipiv, b, ldb, info)
  ! LAPACK's DGBSV contract, over LAPACK's band storage: on entry A(i,j) is
  ! AB(kl+ku+1+i-j, j) for the band, on exit the factors are in the same
  ! place, over the wider band the pivoting fills. The band is expanded, the
  ! dense factorization above is run on it, and the factors are written back:
  ! the operations skipped by a banded factorization are the ones on exact
  ! zeros, so this rounds where a banded one would.
  implicit none
  integer, intent(in) :: n, kl, ku, nrhs, ldab, ldb
  integer, intent(out) :: ipiv(*), info
  double precision, intent(inout) :: ab(ldab,*), b(ldb,*)
  double precision, allocatable :: a(:,:)
  integer :: i, j, kv
  info = 0
  if (n < 0 .or. kl < 0 .or. ku < 0 .or. ldab < 2*kl + ku + 1) then
     info = -1
     return
  end if
  kv = kl + ku
  allocate(a(max(1, n), max(1, n)))
  a = 0.0d0
  do j = 1, n
     do i = max(1, j - ku), min(n, j + kl)
        a(i,j) = ab(kv + 1 + i - j, j)
     end do
  end do
  call recast_ref_gepp(n, nrhs, a, max(1, n), ipiv, b, ldb, info)
  do j = 1, n
     do i = max(1, j - kv), min(n, j + kl)
        ab(kv + 1 + i - j, j) = a(i,j)
     end do
  end do
  deallocate(a)
end subroutine dgbsv
""",
}

_PYTHON_HELPER = '''\
def _recast_ref_2d(x, ld, arg, routine):
    """A Fortran ``(LD,*)`` dummy, as the translation hands one over.

    The emitted call passes the array the source declared, and this reads it
    with the leading dimension the call states -- so the two agree only while
    the array's own first extent *is* that dimension. Anything else is a
    Fortran sequence association nothing here can see through, and it stops
    rather than reading the wrong element.
    """
    if getattr(x, "ndim", 0) != 2 or int(x.shape[0]) != int(ld):
        raise SystemExit(
            "%s: %s was passed with leading dimension %d and shape %r; recast's "
            "reference implementation reads it as a Fortran (LD,*) array"
            % (routine, arg, int(ld), getattr(x, "shape", None))
        )


def _recast_ref_gepp(n, nrhs, a, ipiv, b):
    """Gaussian elimination with partial pivoting; returns LAPACK's INFO.

    Statement for statement the Fortran the reference build compiles for the
    same name, so that the two round alike -- every operation here is one
    IEEE double add, subtract, multiply or divide, in the order the Fortran
    performs it.
    """
    n = int(n)
    nrhs = int(nrhs)
    for k in range(1, n + 1):
        p = k
        amax = abs(a[k - 1, k - 1])
        for i in range(k + 1, n + 1):
            if abs(a[i - 1, k - 1]) > amax:
                amax = abs(a[i - 1, k - 1])
                p = i
        ipiv[k - 1] = p
        if a[p - 1, k - 1] == 0.0:
            return k
        if p != k:
            for j in range(1, n + 1):
                t = a[k - 1, j - 1]
                a[k - 1, j - 1] = a[p - 1, j - 1]
                a[p - 1, j - 1] = t
            for j in range(1, nrhs + 1):
                t = b[k - 1, j - 1]
                b[k - 1, j - 1] = b[p - 1, j - 1]
                b[p - 1, j - 1] = t
        for i in range(k + 1, n + 1):
            a[i - 1, k - 1] = a[i - 1, k - 1] / a[k - 1, k - 1]
        for j in range(k + 1, n + 1):
            for i in range(k + 1, n + 1):
                a[i - 1, j - 1] = a[i - 1, j - 1] - a[i - 1, k - 1] * a[k - 1, j - 1]
        for j in range(1, nrhs + 1):
            for i in range(k + 1, n + 1):
                b[i - 1, j - 1] = b[i - 1, j - 1] - a[i - 1, k - 1] * b[k - 1, j - 1]
    for j in range(1, nrhs + 1):
        for i in range(n, 0, -1):
            t = b[i - 1, j - 1]
            for k in range(i + 1, n + 1):
                t = t - a[i - 1, k - 1] * b[k - 1, j - 1]
            b[i - 1, j - 1] = t / a[i - 1, i - 1]
    return 0


def _recast_ref_stop(routine, info):
    """What a nonzero INFO has to become on this side.

    The Fortran hands INFO back through the argument and the caller decides;
    a translated call cannot write an integer back into its caller's scalar,
    so the one thing this can honestly do with a singular matrix is refuse,
    the way a translated ERROR STOP does. The reference build is not asked
    for this draw: the differential calls the candidate first and draws
    again when it refuses.
    """
    raise SystemExit(
        "%s: recast's reference implementation found no pivot in column %d and "
        "cannot hand INFO back to the translation" % (routine, int(info))
    )
'''

_PYTHON = {
    "dgesv": '''\
def dgesv(n, nrhs, a, lda, ipiv, b, ldb, info=0):
    """DGESV(N, NRHS, A, LDA, IPIV, B, LDB, INFO), recast's own.

    ``a``, ``ipiv`` and ``b`` are updated in place, the way the Fortran
    updates its dummies. ``info`` is accepted and ignored: see
    ``_recast_ref_stop``.
    """
    _recast_ref_2d(a, lda, "a", "dgesv")
    _recast_ref_2d(b, ldb, "b", "dgesv")
    status = _recast_ref_gepp(n, nrhs, a, ipiv, b)
    if status != 0:
        _recast_ref_stop("dgesv", status)
    return status
''',
    "dgbsv": '''\
def dgbsv(n, kl, ku, nrhs, ab, ldab, ipiv, b, ldb, info=0):
    """DGBSV(N, KL, KU, NRHS, AB, LDAB, IPIV, B, LDB, INFO), recast's own.

    LAPACK's band storage: A(i,j) is ``ab[kl+ku+i-j, j-1]``. The band is
    expanded, factored densely and written back over the wider band the
    pivoting fills, which is what the Fortran beside this does.
    """
    _recast_ref_2d(ab, ldab, "ab", "dgbsv")
    _recast_ref_2d(b, ldb, "b", "dgbsv")
    n = int(n)
    kl = int(kl)
    ku = int(ku)
    if n < 0 or kl < 0 or ku < 0 or int(ldab) < 2 * kl + ku + 1:
        raise SystemExit(
            "dgbsv: n=%d, kl=%d, ku=%d and ldab=%d are not a band this can read"
            % (n, kl, ku, int(ldab))
        )
    kv = kl + ku
    a = np.zeros((max(1, n), max(1, n)), dtype=np.float64)
    for j in range(1, n + 1):
        for i in range(max(1, j - ku), min(n, j + kl) + 1):
            a[i - 1, j - 1] = ab[kv + i - j, j - 1]
    status = _recast_ref_gepp(n, nrhs, a, ipiv, b)
    for j in range(1, n + 1):
        for i in range(max(1, j - kv), min(n, j + kl) + 1):
            ab[kv + i - j, j - 1] = a[i - 1, j - 1]
    if status != 0:
        _recast_ref_stop("dgbsv", status)
    return status
''',
}


def supported(names: Iterable[str]) -> list[str]:
    """Those of ``names`` this module has a reference implementation for."""
    return sorted({str(name).lower() for name in names} & SUPPORTED)


def reason(name: str) -> str:
    """What the evidence says about a name this stood in for."""
    return f"{name}: {REASON}"


def fortran_for(names: Iterable[str]) -> str:
    """One compilable file defining every requested name.

    Free-standing subprograms, not a module: the callers were compiled
    against the interface their own tree declared, and what they need
    resolved is the external symbol of that name.
    """
    wanted = supported(names)
    if not wanted:
        return ""
    return "\n".join([_FORTRAN_HEADER, _FORTRAN_HELPER, *(_FORTRAN[name] for name in wanted)])


def python_for(names: Iterable[str]) -> list[str]:
    """The same definitions as emitted-module lines, helper first."""
    wanted = supported(names)
    if not wanted:
        return []
    lines: list[str] = []
    for text in (_PYTHON_HELPER, *(_PYTHON[name] for name in wanted)):
        lines.extend(text.splitlines())
        lines.append("")
    return lines
