"""``f2py-golden``: the untouched Fortran, compiled, as the reference.

Migrated from the build half of the source pipeline's ``diff_driver.py``
and the wrapper rules of ``gen_wrapper.py``. f2py does not translate
anything: it compiles the original source with a real Fortran compiler and
generates glue so Python can call the resulting machine code directly. That
is what makes it a reference -- the thing being compared against *is* the
original program, and bit-exact agreement with it is a meaningful claim.

The wrapper layer exists because f2py's own Fortran parser is shallow. It
cannot resolve use-imported kinds (a silent ``real(4)`` truncation, learned
the hard way), stumbles on derived types, and handles optional arguments
badly. So every subprogram under test gets a flat wrapper subroutine: raw
``real(8)``/``integer`` declarations that need no kind resolution, optional
arguments dropped, dimensions spelled in terms of the other arguments so
f2py can size the outputs.

The cache key folds in everything that can move the reference: the source
digest, every extra source's digest, the compiler's identity and version,
and the flags. Two builds with the same key must behave identically, and a
compiler upgrade changes the key rather than silently invalidating every
downstream Verdict.

The compile itself goes through the executor -- on a laptop that is a
subprocess, on a batch system it is a job -- and the environment is passed
whole plus the compiler overrides, because f2py needs a real PATH to find
its toolchain.
"""

from __future__ import annotations

import hashlib
import importlib
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

from recast.errors import ConfigError, OracleUnavailable, RecastError
from recast.model import Facts, OracleRef, Unit
from recast.plugins.executor import Executor, Job
from recast.plugins.oracle import Oracle

__all__ = ["F2pyGoldenOracle", "factory", "wrappers_for"]

FORTRAN_TYPES = {
    "float64": "real(8)",
    "float32": "real(4)",
    "int32": "integer",
    "int64": "integer(8)",
    "bool": "logical",
    # Fixed width because f2py cannot size len=* dummies; 128 covers every
    # message and name in the corpus, and Fortran comparison semantics pad
    # the shorter operand with blanks anyway.
    "str": "character(len=128)",
}
"""Raw type spellings, no kind parameters: nothing here needs f2py's
crackfortran to resolve a use-imported kind, which it cannot."""

DEFAULT_FLAGS = "-O1 -fno-fast-math -ffp-contract=off"
"""Conservative by default. The reference must round the way the production
build rounds, and aggressive optimization is a second variable nobody asked
to test."""


def wrappers_for(
    record: dict[str, Any],
    subprograms: list[str],
    parameters: dict[str, int] | None = None,
) -> tuple[str, list[str]]:
    """Flat wrapper subroutines for the named subprograms of one module.

    Returns the wrapper source text and the wrapper names, one ``w_<name>``
    per subprogram. Optional arguments are dropped -- the translation spells
    them as keyword sentinels and the differential compares the required
    surface; a specific procedure of a generic is called through the generic
    name, because the specifics are private.

    ``parameters`` are integer constants the argument dimensions name but the
    file use-imports -- a grid's ``pcols`` and ``pver``, say -- emitted as local
    PARAMETERs so f2py can fold the declared shapes (the pipeline's
    ``gen_wrapper --local-params``). A file of bare subprograms gets no
    ``use`` line at all: the callee is an external, and the borrowed module
    name would not compile.
    """
    generic_of = {
        specific: generic
        for generic, specifics in record.get("generics", {}).items()
        for specific in specifics
    }
    table = {s["name"]: s for s in record["subprograms"]}
    module = record["module"]
    is_module = record.get("is_module", True)
    # A submodule cannot be USEd; its procedures are reached through the
    # parent module whose interface declares them (#29).
    module = record.get("submodule_of") or module
    parameter_lines = [
        f"  integer, parameter :: {name} = {int(value)}"
        for name, value in (parameters or {}).items()
    ]
    pieces = ["! Machine-generated by recast (f2py-golden oracle) -- DO NOT EDIT.", ""]
    names = []
    for name in subprograms:
        sub = table[name]
        call_name = generic_of.get(name, name)
        arguments = [a for a in sub["args"] if not a.get("optional")]
        declarations = []
        for argument in arguments:
            spelled = FORTRAN_TYPES.get(argument["dtype"])
            if spelled is None:
                raise ConfigError(
                    f"{name}: argument {argument['name']!r} has dtype "
                    f"{argument['dtype']!r}, which this wrapper cannot spell; "
                    "wrap it by hand or drop the subprogram from the gate"
                )
            intent = {"IN": "in", "OUT": "out", "INOUT": "inout", "UNKNOWN": "inout"}[
                argument["intent"]
            ]
            dims = ""
            if argument.get("dims"):
                dims = "(" + ", ".join(d["ub"] or ":" for d in argument["dims"]) + ")"
            declarations.append(f"  {spelled}, intent({intent}) :: {argument['name']}{dims}")
        argument_names = [a["name"] for a in arguments]
        wrapper = f"w_{name}"
        names.append(wrapper)
        use_line = [f"  use {module}, only: {call_name}"] if is_module else []
        external_line = [] if is_module else [f"  external {call_name}"]
        result_dims = sub.get("result_dims") or [] if sub["kind"] == "function" else []
        if result_dims:
            # An array-valued function result needs its extents too, spelled
            # the way a dummy's are, and f2py cannot wrap an array-valued
            # *function*: the wrapper becomes a subroutine whose ``res`` is
            # an intent(out) dummy. An extent naming neither an argument nor
            # a local parameter becomes a hidden integer dummy (#17).
            if any(d.get("ub") is None for d in result_dims):
                raise ConfigError(
                    f"{name}: array-valued result with a deferred/assumed extent "
                    "is not wrappable; wrap it by hand or drop the subprogram from the gate"
                )
            result = FORTRAN_TYPES.get(sub["result_dtype"], "real(8)")
            extents = [str(d["ub"]) for d in result_dims]
            hidden: list[str] = []
            for extent in extents:
                for token in re.findall(r"[A-Za-z_]\w*", extent):
                    if token not in argument_names and token not in (parameters or {}):
                        if token not in hidden:
                            hidden.append(token)
            declarations += [f"  integer, intent(in) :: {token}" for token in hidden]
            pieces += [
                f"subroutine {wrapper}({', '.join([*argument_names, *hidden, 'res'])})",
                *use_line,
                "  implicit none",
                *parameter_lines,
                *declarations,
                f"  {result}, intent(out) :: res({', '.join(extents)})",
                *([f"  {result}, external :: {call_name}"] if not is_module else []),
                f"  res = {call_name}({', '.join(argument_names)})",
                f"end subroutine {wrapper}",
                "",
            ]
        elif sub["kind"] == "function":
            result = FORTRAN_TYPES.get(sub["result_dtype"], "real(8)")
            pieces += [
                f"function {wrapper}({', '.join(argument_names)}) result(res)",
                *use_line,
                "  implicit none",
                *parameter_lines,
                *declarations,
                f"  {result} :: res",
                *([f"  {result}, external :: {call_name}"] if not is_module else []),
                f"  res = {call_name}({', '.join(argument_names)})",
                f"end function {wrapper}",
                "",
            ]
        else:
            pieces += [
                f"subroutine {wrapper}({', '.join(argument_names)})",
                *use_line,
                "  implicit none",
                *parameter_lines,
                *external_line,
                *declarations,
                f"  call {call_name}({', '.join(argument_names)})",
                f"end subroutine {wrapper}",
                "",
            ]
    return "\n".join(pieces) + "\n", names


def companion_sources(facts: Facts, root: Path) -> list[Path]:
    """The sibling files this unit ``use``s, dependencies first.

    A module that takes its working precision from a kinds module one file
    over does not compile alone: gfortran wants the ``.mod``, and the file
    that would produce it was never handed to the build. The frontend already
    resolved those siblings -- ``Facts.provenance['companions']`` names them
    -- so the reference build asks the facts rather than the operator.

    ``config['extra_sources']`` stays what it always was: files from outside
    the tree, which nothing in the tree can name. Ordering is a topological
    sort over the companions' own ``use`` statements, because a Fortran
    compiler cannot read a module it has not compiled yet, and the ones that
    depend on nothing here come first.
    """
    companions = facts.provenance.get("companions") or []
    by_module = {str(c.get("module", "")).lower(): c for c in companions}
    ordered: list[Path] = []
    placed: set[str] = set()

    def place(name: str, stack: frozenset[str]) -> None:
        companion = by_module.get(name)
        if companion is None or name in placed or name in stack:
            # A cycle is not this build's to resolve -- Fortran allows mutual
            # use only through submodules, and stopping keeps the order total.
            return
        for statement in companion.get("record", {}).get("use_statements", ()):
            match = re.match(r"USE\b\s*(?:,\s*\w+\s*)?(?:::)?\s*(\w+)", statement.strip(), re.I)
            if match:
                place(match.group(1).lower(), stack | {name})
        if name in placed:
            return
        placed.add(name)
        ordered.append((root / companion["source"]).resolve())

    for name in sorted(by_module):
        place(name, frozenset())
    return ordered


def _compiler_version(compiler: str) -> str:
    """The compiler's own version line. A metadata query, not a build --
    which is why it does not go through the executor: the *key* has to fold
    the version in before anyone decides whether to build at all."""
    try:
        out = subprocess.run(  # noqa: S603
            [compiler, "--version"], capture_output=True, text=True, timeout=10, check=False
        )
    except OSError as exc:
        raise ConfigError(
            f"Fortran compiler {compiler!r} is not runnable ({exc}); "
            "install gfortran or point config['fc'] at one"
        ) from exc
    if out.returncode != 0:
        raise ConfigError(f"{compiler!r} --version failed: {out.stderr.strip()[:200]}")
    return out.stdout.splitlines()[0].strip()


class F2pyGoldenOracle(Oracle):
    """Compile the untouched Fortran and hand back a callable truth module."""

    name = "f2py-golden"
    cost = "build"

    def key(self, unit: Unit, facts: Facts, config: dict[str, Any]) -> str:
        compiler = config.get("fc", "gfortran")
        digest = hashlib.sha256()
        digest.update(str(facts.provenance.get("digest")).encode())
        root = Path(config.get("root", "."))
        extras = [str(s) for s in config.get("extra_sources", [])]
        extras += [str(s) for s in companion_sources(facts, root)]
        for extra in sorted(extras):
            path = Path(extra)
            digest.update(extra.encode())
            if path.is_file():
                digest.update(hashlib.sha256(path.read_bytes()).hexdigest().encode())
        digest.update(_compiler_version(compiler).encode())
        digest.update(config.get("fflags", DEFAULT_FLAGS).encode())
        digest.update(str(sorted((config.get("wrapper_parameters") or {}).items())).encode())
        digest.update(",".join(self._subprograms(facts, config)).encode())
        return f"f2py:{facts.interface.get('module', unit.uid)}:{digest.hexdigest()[:16]}"

    def materialize(
        self,
        unit: Unit,
        facts: Facts,
        workspace: Path,
        executor: Executor,
        config: dict[str, Any],
    ) -> OracleRef:
        key = self.key(unit, facts, config)
        build = workspace / f"oracle-{key.rsplit(':', 1)[-1]}"
        build.mkdir(parents=True, exist_ok=True)

        source = (Path(config.get("root", ".")) / facts.provenance["source"]).resolve()
        subprograms = self._subprograms(facts, config)
        if not subprograms:
            # Nothing callable to wrap -- a module of kind parameters, or of
            # abstract interfaces. f2py is happy to build an extension with an
            # empty ``only:`` list, and importing the result segfaults the
            # interpreter, which no ``except`` can catch and which takes the
            # whole run with it. A reference to nothing is not a reference.
            raise OracleUnavailable(
                f"{unit.uid}: no public subprogram to wrap; there is no reference to build"
            )
        wrapper_text, wrapper_names = wrappers_for(
            facts.interface, subprograms, parameters=config.get("wrapper_parameters")
        )
        (build / "wrappers.f90").write_text(wrapper_text)

        compiler = config.get("fc", "gfortran")
        module_name = f"ref_{facts.interface['module']}"
        # Companions first, then whatever the operator added, then the unit's
        # own source: gfortran compiles in argument order and a ``use`` of a
        # module later in the list is a fatal "cannot open module file".
        sources = [
            *[str(s) for s in companion_sources(facts, Path(config.get("root", ".")))],
            *[str(Path(s).resolve()) for s in config.get("extra_sources", [])],
            str(source),
            "wrappers.f90",
        ]
        # A Fortran ``include`` is resolved against the compiler's search path,
        # not against the file that wrote it, and this build runs in its own
        # directory -- so every directory a source came from goes on the path
        # or a library that keeps its constants in a ``.inc`` beside the code
        # cannot be compiled at all.
        includes = " ".join(
            f"-I{d}" for d in dict.fromkeys(str(Path(s).resolve().parent) for s in sources[:-1])
        )
        flags = f"{config.get('fflags', DEFAULT_FLAGS)} {includes}".strip()
        job = Job(
            argv=[
                sys.executable,
                "-m",
                "numpy.f2py",
                "-c",
                *sources,
                "-m",
                module_name,
                "only:",
                *wrapper_names,
                ":",
                f"--f90flags={flags}",
                f"--f77flags={flags}",
                "--backend",
                "meson",
            ],
            cwd=build,
            # The whole environment plus the compiler overrides: f2py needs a
            # real PATH, and the local executor passes exactly what it is given.
            # The interpreter's own bin directory rides in front so the build
            # backend (meson, ninja) installed beside numpy is found.
            env={
                **os.environ,
                "PATH": f"{Path(sys.executable).parent}{os.pathsep}{os.environ.get('PATH', '')}",
                "FC": compiler,
                "F90": compiler,
            },
            timeout_s=float(config.get("build_timeout", 600)),
            label=f"f2py {module_name}",
        )
        try:
            result = executor.run(job)
        except RecastError:
            raise
        except Exception as error:
            # An executor that refuses -- it cannot honestly supply what the job
            # asked for -- is the case ``OracleUnavailable`` exists for, and it
            # has to arrive as one. The runner catches ``RecastError`` and marks
            # this unit's oracle stage failed; anything else escapes it and takes
            # the whole run down, so a refusal nobody wrapped costs the other
            # units their verdicts as well as this one.
            raise OracleUnavailable(
                f"executor {getattr(executor, 'name', type(executor).__name__)!r} did not "
                f"run the f2py build for {unit.uid}: {type(error).__name__}: {error}"
            ) from error
        if not result.ok:
            log = build / "f2py.log"
            log.write_text(result.stdout + "\n" + result.stderr)
            raise ConfigError(
                f"f2py build for {unit.uid} failed (exit {result.returncode}); log at {log}"
            )

        sys.path.insert(0, str(build))
        try:
            module = importlib.import_module(module_name)
        finally:
            sys.path.remove(str(build))
        return OracleRef(
            unit=unit.uid,
            oracle=self.name,
            key=key,
            handle={
                "module": module,
                "wrappers": dict(zip(subprograms, wrapper_names, strict=True)),
                "build_dir": build,
            },
            cost=self.cost,
        )

    @staticmethod
    def _subprograms(facts: Facts, config: dict[str, Any]) -> list[str]:
        named = config.get("subprograms")
        if named:
            return list(named)
        # Public only, because the wrappers `use` the module: a private
        # symbol is not importable and the build fails on the whole file.
        return [s["name"] for s in facts.interface["subprograms"] if s.get("public", True)]


def factory(**_config: Any) -> F2pyGoldenOracle:
    return F2pyGoldenOracle()
