"""``f2py-golden``: the untouched Fortran, compiled, as the reference.

Migrated from the build half of CESM-language-translator ``diff_driver.py``
and the wrapper rules of ``gen_wrapper.py``. f2py does not translate
anything: it compiles the original source with a real Fortran compiler and
generates glue so Python can call the resulting machine code directly. That
is what makes it a reference -- the thing being compared against *is* the
original program, and bit-exact agreement with it is a meaningful claim.

The wrapper layer exists because f2py's own Fortran parser is shallow. It
cannot resolve use-imported kinds (a silent ``real(4)`` truncation, learned
the hard way), stumbles on derived types, and handles optional arguments
badly. So every subprogram under test gets a flat wrapper subroutine: raw
``real(8)``/``integer`` declarations that need no kind resolution, optional
arguments dropped, dimensions spelled in terms of the other arguments so
f2py can size the outputs.

The cache key folds in everything that can move the reference: the source
digest, every extra source's digest, the compiler's identity and version,
and the flags. Two builds with the same key must behave identically, and a
compiler upgrade changes the key rather than silently invalidating every
downstream Verdict.

The compile itself goes through the executor -- on a laptop that is a
subprocess, on a batch system it is a job -- and the environment is passed
whole plus the compiler overrides, because f2py needs a real PATH to find
its toolchain.
"""

from __future__ import annotations

import hashlib
import importlib
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

from recast.errors import ConfigError
from recast.model import Facts, OracleRef, Unit
from recast.plugins.executor import Executor, Job
from recast.plugins.oracle import Oracle

__all__ = ["F2pyGoldenOracle", "factory", "wrappers_for"]

FORTRAN_TYPES = {
    "float64": "real(8)",
    "float32": "real(4)",
    "int32": "integer",
    "int64": "integer(8)",
    "bool": "logical",
    # Fixed width because f2py cannot size len=* dummies; 128 covers every
    # message and name in the corpus, and Fortran comparison semantics pad
    # the shorter operand with blanks anyway.
    "str": "character(len=128)",
}
"""Raw type spellings, no kind parameters: nothing here needs f2py's
crackfortran to resolve a use-imported kind, which it cannot."""

DEFAULT_FLAGS = "-O1 -fno-fast-math -ffp-contract=off"
"""Conservative by default. The reference must round the way the production
build rounds, and aggressive optimization is a second variable nobody asked
to test."""


def wrappers_for(record: dict[str, Any], subprograms: list[str]) -> tuple[str, list[str]]:
    """Flat wrapper subroutines for the named subprograms of one module.

    Returns the wrapper source text and the wrapper names, one ``w_<name>``
    per subprogram. Optional arguments are dropped -- the translation spells
    them as keyword sentinels and the differential compares the required
    surface; a specific procedure of a generic is called through the generic
    name, because the specifics are private.
    """
    generic_of = {
        specific: generic
        for generic, specifics in record.get("generics", {}).items()
        for specific in specifics
    }
    table = {s["name"]: s for s in record["subprograms"]}
    module = record["module"]
    pieces = ["! Machine-generated by recast (f2py-golden oracle) -- DO NOT EDIT.", ""]
    names = []
    for name in subprograms:
        sub = table[name]
        call_name = generic_of.get(name, name)
        arguments = [a for a in sub["args"] if not a.get("optional")]
        declarations = []
        for argument in arguments:
            spelled = FORTRAN_TYPES.get(argument["dtype"])
            if spelled is None:
                raise ConfigError(
                    f"{name}: argument {argument['name']!r} has dtype "
                    f"{argument['dtype']!r}, which this wrapper cannot spell; "
                    "wrap it by hand or drop the subprogram from the gate"
                )
            intent = {"IN": "in", "OUT": "out", "INOUT": "inout", "UNKNOWN": "inout"}[
                argument["intent"]
            ]
            dims = ""
            if argument.get("dims"):
                dims = "(" + ", ".join(d["ub"] or ":" for d in argument["dims"]) + ")"
            declarations.append(f"  {spelled}, intent({intent}) :: {argument['name']}{dims}")
        argument_names = [a["name"] for a in arguments]
        wrapper = f"w_{name}"
        names.append(wrapper)
        if sub["kind"] == "function":
            result = FORTRAN_TYPES.get(sub["result_dtype"], "real(8)")
            pieces += [
                f"function {wrapper}({', '.join(argument_names)}) result(res)",
                f"  use {module}, only: {call_name}",
                "  implicit none",
                *declarations,
                f"  {result} :: res",
                f"  res = {call_name}({', '.join(argument_names)})",
                f"end function {wrapper}",
                "",
            ]
        else:
            pieces += [
                f"subroutine {wrapper}({', '.join(argument_names)})",
                f"  use {module}, only: {call_name}",
                "  implicit none",
                *declarations,
                f"  call {call_name}({', '.join(argument_names)})",
                f"end subroutine {wrapper}",
                "",
            ]
    return "\n".join(pieces) + "\n", names


def _compiler_version(compiler: str) -> str:
    """The compiler's own version line. A metadata query, not a build --
    which is why it does not go through the executor: the *key* has to fold
    the version in before anyone decides whether to build at all."""
    try:
        out = subprocess.run(  # noqa: S603
            [compiler, "--version"], capture_output=True, text=True, timeout=10, check=False
        )
    except OSError as exc:
        raise ConfigError(
            f"Fortran compiler {compiler!r} is not runnable ({exc}); "
            "install gfortran or point config['fc'] at one"
        ) from exc
    if out.returncode != 0:
        raise ConfigError(f"{compiler!r} --version failed: {out.stderr.strip()[:200]}")
    return out.stdout.splitlines()[0].strip()


class F2pyGoldenOracle(Oracle):
    """Compile the untouched Fortran and hand back a callable truth module."""

    name = "f2py-golden"
    cost = "build"

    def key(self, unit: Unit, facts: Facts, config: dict[str, Any]) -> str:
        compiler = config.get("fc", "gfortran")
        digest = hashlib.sha256()
        digest.update(str(facts.provenance.get("digest")).encode())
        for extra in sorted(str(s) for s in config.get("extra_sources", [])):
            path = Path(extra)
            digest.update(extra.encode())
            if path.is_file():
                digest.update(hashlib.sha256(path.read_bytes()).hexdigest().encode())
        digest.update(_compiler_version(compiler).encode())
        digest.update(config.get("fflags", DEFAULT_FLAGS).encode())
        digest.update(",".join(self._subprograms(facts, config)).encode())
        return f"f2py:{facts.interface.get('module', unit.uid)}:{digest.hexdigest()[:16]}"

    def materialize(
        self,
        unit: Unit,
        facts: Facts,
        workspace: Path,
        executor: Executor,
        config: dict[str, Any],
    ) -> OracleRef:
        key = self.key(unit, facts, config)
        build = workspace / f"oracle-{key.rsplit(':', 1)[-1]}"
        build.mkdir(parents=True, exist_ok=True)

        source = (Path(config.get("root", ".")) / facts.provenance["source"]).resolve()
        subprograms = self._subprograms(facts, config)
        wrapper_text, wrapper_names = wrappers_for(facts.interface, subprograms)
        (build / "wrappers.f90").write_text(wrapper_text)

        compiler = config.get("fc", "gfortran")
        module_name = f"ref_{facts.interface['module']}"
        sources = [
            *[str(Path(s).resolve()) for s in config.get("extra_sources", [])],
            str(source),
            "wrappers.f90",
        ]
        job = Job(
            argv=[
                sys.executable,
                "-m",
                "numpy.f2py",
                "-c",
                *sources,
                "-m",
                module_name,
                "only:",
                *wrapper_names,
                ":",
                f"--f90flags={config.get('fflags', DEFAULT_FLAGS)}",
                "--backend",
                "meson",
            ],
            cwd=build,
            # The whole environment plus the compiler overrides: f2py needs a
            # real PATH, and the local executor passes exactly what it is given.
            # The interpreter's own bin directory rides in front so the build
            # backend (meson, ninja) installed beside numpy is found.
            env={
                **os.environ,
                "PATH": f"{Path(sys.executable).parent}{os.pathsep}{os.environ.get('PATH', '')}",
                "FC": compiler,
                "F90": compiler,
            },
            timeout_s=float(config.get("build_timeout", 600)),
            label=f"f2py {module_name}",
        )
        result = executor.run(job)
        if not result.ok:
            log = build / "f2py.log"
            log.write_text(result.stdout + "\n" + result.stderr)
            raise ConfigError(
                f"f2py build for {unit.uid} failed (exit {result.returncode}); log at {log}"
            )

        sys.path.insert(0, str(build))
        try:
            module = importlib.import_module(module_name)
        finally:
            sys.path.remove(str(build))
        return OracleRef(
            unit=unit.uid,
            oracle=self.name,
            key=key,
            handle={
                "module": module,
                "wrappers": dict(zip(subprograms, wrapper_names, strict=True)),
                "build_dir": build,
            },
            cost=self.cost,
        )

    @staticmethod
    def _subprograms(facts: Facts, config: dict[str, Any]) -> list[str]:
        named = config.get("subprograms")
        if named:
            return list(named)
        return [s["name"] for s in facts.interface["subprograms"]]


def factory(**_config: Any) -> F2pyGoldenOracle:
    return F2pyGoldenOracle()
