"""Record a flat adapter's inputs and outputs from a real run.

A routine that checks its own energy balance against inputs it did not
compute aborts on generated inputs, on both sides, and the sampled gate has
nothing to say about it. What it needs is the state the model actually
hands it: a recording. The engine's ``dump-replay`` oracle replays one;
this module makes one.

From the same ``FlatPlan`` the adapters come from, it generates:

* a Fortran **recorder module** with one probe per adapted subprogram,
  ``rec_<name>(phase, <original dummies>)``: phase 0, before the call, opens
  a dump file and writes the scalar dummies, the patch count and every
  touched component as ``# INPUT``; phase 1, after the call, writes the
  written components as ``# OUTPUT``. The first ``calls`` calls of each
  probe are recorded, in the engine's dump format, Fortran order;
* a **probed copy** of the staged tree, in which every ``call <Name>(...)``
  of an adapted subprogram is bracketed by the two probe calls, and the
  calling module ``use``s the recorder.

Nothing in the tree the frontend reads is touched: the copy lives beside
the other generated trees. Building and running the probed copy is the
case's business -- its compiler, its flags, its namelist -- and so is
writing them down beside the dumps, because the dump format has nowhere to
put a build identity.

What the recording is: the model's own operating point, with every
correlation between components the sampler could never produce. What it
is not: coverage beyond the calls that were recorded.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path
from typing import Any

from recast.fortran.flatten import DERIVED, FlatPlan, plans_from_facts

__all__ = ["RECORDER_MODULE", "plans_for_units", "probe_tree", "recorder_module"]

RECORDER_MODULE = "recast_recorder"
CALL = re.compile(r"^(?P<pad>\s*)call\s+(?P<name>\w+)\s*\((?P<args>[^!]*)\)\s*(?:!.*)?$", re.I)
FORTRAN_TYPES = {"float64": "real(8)", "float32": "real(4)", "int32": "integer", "bool": "logical"}
WRITERS = {"int32": "rec_i1", "bool": "rec_l1"}


def _dims_text(extents: list[str]) -> str:
    return "(" + ",".join(extents) + ")" if extents else ""


def _dims_lines_for(target: str, rank: int) -> list[str]:
    """``dims`` from ``size()`` of any array, per axis -- the run's extents,
    not the plan's, because a module variable may size an axis."""
    if not rank:
        return ["       dims = ''"]
    pieces = ["'('"]
    for axis in range(rank):
        if axis:
            pieces.append("','")
        pieces.append(f"size({target}, {axis + 1})")
    pieces.append("')'")
    fmt = "(" + ",".join("a" if p.startswith("'") else "i0" for p in pieces) + ")"
    return [f"       write (dims, '{fmt}') {', '.join(pieces)}"]


def _flat_view(target: str, rank: int) -> str:
    """The array as rank-1 for the writers: a scalar becomes a one-element
    array constructor."""
    if not rank:
        return f"(/{target}/)"
    return f"reshape({target}, (/size({target})/))"


def _record_call(
    lines: list[str],
    unit: str,
    tag: str,
    label: str,
    target: str,
    rank: int,
    dtype: str,
    dims: str | None = None,
) -> None:
    """One ``call rec_*`` writing ``target`` under ``label``; the extents
    from ``size()`` at run time unless ``dims`` spells them."""
    writer = WRITERS.get(dtype, "rec_r1")
    if dims is None:
        lines.extend(_dims_lines_for(target, rank))
        spelled = "trim(dims)"
    else:
        spelled = f"'{dims}'"
    lines.append(
        f"       call {writer}({unit}, '{tag}', '{label}', {spelled}, {_flat_view(target, rank)})"
    )


def recorder_module(
    module: str,
    plans: list[FlatPlan],
    calls: int = 40,
    name: str = RECORDER_MODULE,
    window: tuple[str, str, int, int] | None = None,
) -> str:
    """The Fortran recorder for the adapted subprograms of ``module``.

    ``window`` is ``(module, variable, first, last)``: an integer the model
    keeps -- its step counter -- and the closed range of its values during
    which calls are recorded. A recording of the first ``calls`` calls is a
    recording of the model's start, and a gate on it is blind to what only
    a later state exercises; ``window`` is how a recording of day 15 is
    made without recording the fourteen days before it.
    """
    used: dict[str, set[str]] = {}
    if window is not None:
        used.setdefault(window[0], set()).add(window[1])
    types: dict[str, str | None] = {}
    for plan in plans:
        for obj in plan.objects:
            types[obj.type_name] = obj.type_module
            if obj.kind == "state" and obj.module:
                used.setdefault(obj.module, set()).add(obj.name)
        for state in plan.states:
            used.setdefault(state.module, set()).add(state.name)
    lines = [
        "! Machine-generated by RecastEngine (recast.oracle.record) -- DO NOT EDIT.",
        f"module {name}",
    ]
    for type_name, type_module in sorted(types.items()):
        lines.append(f"  use {type_module or type_name}, only: {type_name}")
    for mod, names in sorted(used.items()):
        lines.append(f"  use {mod}, only: {', '.join(sorted(names))}")
    lines += [
        "  implicit none",
        "  private",
        f"  integer, parameter :: max_calls = {calls}",
        "  character(len=512), public, save :: recast_dump_dir = 'dumps'",
    ]
    for plan in plans:
        sub = plan.subprogram["name"]
        lines.append(f"  integer, save :: n_{sub} = 0")
        lines.append(f"  integer, save :: u_{sub} = -1")
        lines.append(f"  public :: rec_{sub}")
    lines.append("contains")
    lines += [
        "",
        "  subroutine rec_open(unit, name, call_no)",
        "    integer, intent(out) :: unit",
        "    character(len=*), intent(in) :: name",
        "    integer, intent(in) :: call_no",
        "    character(len=600) :: path",
        "    write (path, '(a,a,a,a,i4.4,a)') "
        "trim(recast_dump_dir), '/', name, '_', call_no, '.txt'",
        "    open (newunit=unit, file=trim(path), action='write', status='replace')",
        "  end subroutine rec_open",
        "",
        "  subroutine rec_r1(unit, tag, name, dims, a)",
        "    integer, intent(in) :: unit",
        "    character(len=*), intent(in) :: tag, name, dims",
        "    real(8), intent(in) :: a(:)",
        "    integer :: i",
        "    write (unit, '(a,a,a,a,a)') '# ', tag, ': ', name, dims",
        "    do i = 1, size(a)",
        "       write (unit, '(es25.17e3)') a(i)",
        "    end do",
        "  end subroutine rec_r1",
        "",
        "  subroutine rec_i1(unit, tag, name, dims, a)",
        "    integer, intent(in) :: unit",
        "    character(len=*), intent(in) :: tag, name, dims",
        "    integer, intent(in) :: a(:)",
        "    integer :: i",
        "    write (unit, '(a,a,a,a,a)') '# ', tag, ': ', name, dims",
        "    do i = 1, size(a)",
        "       write (unit, '(i0)') a(i)",
        "    end do",
        "  end subroutine rec_i1",
        "",
        "  subroutine rec_l1(unit, tag, name, dims, a)",
        "    integer, intent(in) :: unit",
        "    character(len=*), intent(in) :: tag, name, dims",
        "    logical, intent(in) :: a(:)",
        "    integer :: i",
        "    write (unit, '(a,a,a,a,a)') '# ', tag, ': ', name, dims",
        "    do i = 1, size(a)",
        "       if (a(i)) then",
        "          write (unit, '(a)') '1'",
        "       else",
        "          write (unit, '(a)') '0'",
        "       end if",
        "    end do",
        "  end subroutine rec_l1",
    ]
    for plan in plans:
        sub = plan.subprogram
        sname = sub["name"]
        patch = plan.patch_count
        originals = [a for a in sub["args"] if not a.get("optional")]
        dummies = ", ".join(a["name"] for a in originals)
        lines += [
            "",
            f"  subroutine rec_{sname}(phase, {dummies})",
            "    integer, intent(in) :: phase",
        ]
        for a in originals:
            derived = DERIVED.match(str(a["dtype"]))
            if derived:
                lines.append(f"    type({derived.group(1).lower()}) :: {a['name']}")
            else:
                spelled = FORTRAN_TYPES[str(a["dtype"])]
                dims = "(" + ",".join(":" for _ in a["dims"]) + ")" if a.get("dims") else ""
                lines.append(f"    {spelled}, intent(in) :: {a['name']}{dims}")
        passes_patch = any(a["name"].lower() == patch.lower() for a in originals)
        if not passes_patch:
            # CLUBB passes ngrdcol as a dummy; then it is already declared and
            # already the run's value, and a local of the same name would be
            # a second declaration.
            lines.append(f"    integer :: {patch}")
        lines.append("    character(len=128) :: dims")
        # The patch count from the first component allocated over it.
        first = next(
            (
                (obj, comp)
                for obj in plan.objects
                for comp in obj.components
                if comp.extents and comp.extents[0] == patch
            ),
            None,
        )
        if passes_patch:
            pass
        elif first is None:
            lines.append(f"    {patch} = 1")
        else:
            lines.append(f"    {patch} = size({first[0].name}%{first[1].name}, 1)")
        u = f"u_{sname}"
        if window is not None:
            _, counter, lo, hi = window
            lines.append(f"    if ({counter} < {lo} .or. {counter} > {hi}) return")
        lines += [
            "    if (phase == 0) then",
            f"       n_{sname} = n_{sname} + 1",
            f"       if (n_{sname} > max_calls) return",
            f"       call rec_open({u}, '{sname}_flat', n_{sname})",
            f"       write ({u}, '(a,i0)') '# PROBE {module}.{sname}_flat: call=', n_{sname}",
        ]
        for a in originals:
            if DERIVED.match(str(a["dtype"])) or a.get("dims"):
                continue
            fmt = {"int32": "i0", "bool": "l1"}.get(str(a["dtype"]), "es25.17e3")
            lines.append(f"       write ({u}, '(a,{fmt})') '# {a['name']} = ', {a['name']}")
        lines.append(f"       write ({u}, '(a,i0)') '# {patch} = ', {patch}")
        for extent, (owner, member, axis) in plan.extent_args.items():
            # An extent the plan could not spell: the run's own, from size().
            lines.append(
                f"       write ({u}, '(a,i0)') '# {extent} = ', size({owner}%{member}, {axis})"
            )

        for a in originals:
            if a.get("dims") and not DERIVED.match(str(a["dtype"])):
                _record_call(
                    lines, u, "INPUT", a["name"], a["name"], len(a["dims"]), str(a["dtype"])
                )
        for obj in plan.objects:
            for comp in obj.components:
                _record_call(
                    lines,
                    u,
                    "INPUT",
                    comp.flat,
                    f"{obj.name}%{comp.name}",
                    len(comp.extents),
                    comp.dtype,
                )
        for state in plan.states:
            _record_call(
                lines,
                u,
                "INPUT",
                state.flat,
                state.name,
                len(state.extents),
                state.dtype,
                _dims_text(state.extents),
            )
        lines += ["    else", f"       if (n_{sname} > max_calls) return"]
        for obj in plan.objects:
            for comp in obj.components:
                if comp.written:
                    _record_call(
                        lines,
                        u,
                        "OUTPUT",
                        comp.flat,
                        f"{obj.name}%{comp.name}",
                        len(comp.extents),
                        comp.dtype,
                    )
        for a in originals:
            if a.get("dims") and not DERIVED.match(str(a["dtype"])) and a["intent"] != "IN":
                _record_call(
                    lines, u, "OUTPUT", a["name"], a["name"], len(a["dims"]), str(a["dtype"])
                )
        for state in plan.states:
            if state.written:
                _record_call(
                    lines,
                    u,
                    "OUTPUT",
                    state.flat,
                    state.name,
                    len(state.extents),
                    state.dtype,
                    _dims_text(state.extents),
                )
        lines += [f"       close ({u})", "    end if", f"  end subroutine rec_{sname}"]
    lines.append(f"end module {name}")
    return "\n".join(lines) + "\n"


def _strip_comment(line: str) -> str:
    """The code part of a line: a ``!`` outside quotes starts a comment."""
    out, quote = [], None
    for ch in line:
        if quote:
            out.append(ch)
            if ch == quote:
                quote = None
        elif ch in ("'", '"'):
            quote = ch
            out.append(ch)
        elif ch == "!":
            break
        else:
            out.append(ch)
    return "".join(out)


def _continues(line: str) -> bool:
    return _strip_comment(line).rstrip().endswith("&")


def _split_actuals(text: str) -> list[str]:
    """Split an actual-argument list on top-level commas only."""
    parts: list[str] = []
    depth = 0
    current: list[str] = []
    for ch in text:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(ch)
    if current:
        parts.append("".join(current))
    return parts


def probe_tree(
    staged: Path,
    out: Path,
    plans_by_module: dict[str, list[FlatPlan]],
    name: str = RECORDER_MODULE,
) -> dict[str, int]:
    """Copy ``staged`` to ``out`` with every call of an adapted subprogram
    bracketed by its probes. Returns ``{subprogram: sites}``."""
    if out.exists():
        shutil.rmtree(out)
    shutil.copytree(staged, out)
    targets = {
        plan.subprogram["name"].lower(): plan
        for plans in plans_by_module.values()
        for plan in plans
    }
    sites: dict[str, int] = {}
    for path in sorted(out.glob("*.f90")):
        text = path.read_text(errors="replace")
        lines = text.splitlines()
        changed = False
        result: list[str] = []
        i = 0
        while i < len(lines):
            # A call may continue over several lines: gather the statement.
            span = [lines[i]]
            while _continues(span[-1]) and i + len(span) < len(lines):
                span.append(lines[i + len(span)])
            # ``a, & ! In`` leaves a space between the ampersand and the
            # comment it trailed: strip blanks before the ampersands.
            logical = " ".join(
                _strip_comment(ln).strip().rstrip("&").strip().lstrip("&").strip() for ln in span
            )
            match = CALL.match(" " * (len(span[0]) - len(span[0].lstrip())) + logical.strip())
            called = match.group("name").lower() if match else None
            if match and called and called in targets:
                pad, args = match.group("pad"), match.group("args").strip()
                plan = targets[called]
                keep = [a for a in plan.subprogram["args"] if not a.get("optional")]
                actuals = [a.strip() for a in _split_actuals(args)]
                if len(actuals) != len(plan.subprogram["args"]) and len(actuals) != len(keep):
                    result.extend(span)
                    i += len(span)
                    continue
                passed = ", ".join(actuals[: len(keep)])
                result.append(f"{pad}call rec_{called}(0, {passed})")
                result.extend(span)
                result.append(f"{pad}call rec_{called}(1, {passed})")
                sites[called] = sites.get(called, 0) + 1
                changed = True
            else:
                result.extend(span)
            i += len(span)
        if changed:
            text = "\n".join(result) + "\n"
            text = re.sub(
                r"^(\s*module\s+\w+\s*\n)",
                rf"\1  use {name}\n",
                text,
                count=1,
                flags=re.I | re.M,
            )
            path.write_text(text)
    return sites


def plans_for_units(facts_by_module: dict[str, Any]) -> dict[str, list[FlatPlan]]:
    """``{module: usable plans}`` from each unit's Facts, empty ones dropped."""
    out: dict[str, list[FlatPlan]] = {}
    for module, facts in facts_by_module.items():
        plans = plans_from_facts(facts)
        if plans:
            out[module] = plans
    return out
