"""The generated constants modules, rendered from the frontend's records.

Two files every translation ships beside the module it emits. The constants
module carries the zero-literal rule's other half: every parameter and every
hoisted literal, spelled once, with the source location that justifies it --
the generated module reads ``F_273P15`` from here, and this file is the only
place that says what that name means. The use-constants module carries the
constants the source imported from modules that are not being translated,
rendered from the same parsed expressions that the oracle's Fortran stand-in
is built from, so the two sides agree bit-for-bit by construction.

The frontend already classified everything (``constants.extract`` records a
``kind`` and ``payload`` per parameter; ``use.resolve`` returns ``Expr``
trees); this module only decides spelling. A parameter the frontend could not
classify comes out as a ``# SKIPPED`` comment line, not a guess -- the value
of a parameter is a number the Fortran compiler folded, and folding it
differently here is a wrong answer nothing downstream re-checks.
"""

from __future__ import annotations

import ast
import inspect
import re
from pathlib import PurePath, PurePosixPath
from typing import Any

from recast.fortran.expr import (
    PYTHON_POWER,
    PYTHON_QUOTIENT,
    Expr,
    UnsupportedExpression,
    fold_check,
    int_div,
    int_pow,
    python_call,
    render,
    typed,
    with_integer_division,
)

__all__ = [
    "constant_expression",
    "constants_module",
    "defined_module_parameters",
    "np_int_literal",
    "use_constants_module",
]

LEADING_ZERO = re.compile(r"^0\d")


def constants_module(record: dict[str, Any], *, extern: tuple[tuple[str, int], ...] = ()) -> str:
    """The generated constants file for one module, from its constants record.

    ``extern`` names sibling generated constants modules to star-import, as
    ``(stem, how many names it supplies)`` -- the count is documentation for
    whoever reads the generated file, not information the import needs.
    """
    # The file's name, never the path it was found at: an absolute path in a
    # generated file makes the artifact differ between two machines that
    # translated the same source, and ``Candidate.digest()`` with it. The
    # pipeline this reproduces emitted whatever path its command line was
    # given; ``tools/emit_diff.py`` normalizes that away rather than the engine
    # reproducing a reproducibility defect.
    source_name = PurePosixPath(str(record["source_file"])).name
    lines = [
        '"""Machine-generated by recast — DO NOT EDIT."""',
        f"# source: {source_name} (module {record['module']})",
        "",
        "import numpy as np",
        "",
    ]
    for stem, count in extern:
        lines.append(f"from {stem} import *  # noqa: F401,F403 (use-imported params: {count})")
        lines.append("")

    lines.append("# ----- module-level parameters")
    for parameter in record["module_parameters"]:
        lines.append(_module_parameter(parameter, source_name))
    lines.append("")

    lines.append("# ----- subprogram-local parameters")
    for parameter in record["local_parameters"]:
        lines.append(_local_parameter(parameter))
    lines.append("")

    lines.append("# ----- hoisted execution-part literals (zero-literal rule)")
    for name in sorted(record["hoisted_literals"]):
        entry = record["hoisted_literals"][name]
        lines.append(_hoisted(name, entry))
    lines.append("")
    return "\n".join(_with_helpers(lines, 5))


def defined_module_parameters(record: dict[str, Any]) -> set[str]:
    """The upper-case names the module's constants file actually defines.

    A sibling module referring to this module's parameter spells it as the
    constants file does when the file has it, and lower-case when the
    frontend could not classify it and the file carries a ``# SKIPPED``
    line instead. Asked of the renderer so the answer cannot disagree with
    the file.
    """
    return {
        parameter["name"].upper()
        for parameter in record["module_parameters"]
        if not _module_parameter(parameter, "").startswith("# SKIPPED")
    }


def constant_expression(text: str, record: dict[str, Any], dtype: str) -> str | None:
    """A constant expression outside a parameter declaration, spelled the way
    the constants file spells a parameter's and converted to ``dtype``, or
    ``None``.

    A component's default initialization is one -- ``cnt = n + 1_wi``, the
    "not yet seeded" sentinel mt19937's state starts at -- and nothing but
    this route knows how to spell an expression over the module's own
    parameters. Classified by the same classifier over the parameters the
    constants file defines (``record`` is the frontend's constants record),
    and typed as a parameter's initializer is (``_typed_expression``); a
    literal or a lone name is left to the caller's own forms, and anything
    the classifier refuses is ``None``.

    The value is then the thing it initializes, as Fortran's intrinsic
    assignment converts it (F2018 10.2.1.3): ``integer :: kk = grav * 2``
    is 19, truncated, and ``real :: sx = c4 * 3`` the single nearest 0.3 --
    the expression's own value, 19.62 and a double, was what the component
    held. An INTEGER target of a real expression is its ``int``, and one
    whose operands' kinds are not known is ``None``: truncating an integer
    is harmless, but not truncating a real is the wrong number. A single
    is rounded to single before it is widened, as ``_stored`` rounds a
    single parameter; a double given an integer expression is its float64.
    """
    from recast.fortran.constants import Kinds, classify_init

    parameters = record.get("module_parameters") or []
    known = {p["name"] for p in parameters if p.get("kind") != "skip"}
    dtypes = {p["name"]: p.get("dtype") for p in parameters}
    kind, payload = classify_init(text, known, kinds=Kinds(dtypes=dtypes))
    if kind != "expr":
        return None
    spelled = _typed_expression(payload)
    try:
        tree = ast.parse(spelled, mode="eval")
    except SyntaxError:
        return None
    valued = _IntegerArithmetic(_token_types(payload)).kind(tree.body)
    if dtype.startswith("int"):
        if valued is None:
            return None
        return spelled if valued == "int" else f"int({spelled})"
    if dtype == "float32":
        return _stored(spelled, {"dtype": "float32", "kind": "expr"})
    if dtype == "float64" and valued == "int":
        return f"np.float64({spelled})"
    return spelled


def np_int_literal(value: int) -> str:
    """An integer constant, in the narrowest of int32/int64 that holds it.

    Fortran's default INTEGER is 32-bit and this backend spelled every
    non-``int64`` constant ``np.int32(...)``, which numpy refuses outright:
    a mask or a multiplier that does not fit -- ``Z'9908B0DF'``, an
    mt19937_64 constant -- raises ``OverflowError`` while the module is
    still being imported, so nothing in the translation runs.

    The width comes from the *value* rather than the declared kind, which is
    what keeps this from being a formatting change: every constant that
    already fit stays byte-identical, and only the ones that could not be
    emitted at all move. The declared kind is the better answer and this is
    not it -- an explicitly ``int64`` literal small enough to fit narrows to
    int32 here, which is harmless while the bit intrinsics coerce to Python
    ``int``, and wrong the moment one of them starts respecting a width.
    """
    return f"np.int64({value})" if not -(2**31) <= value < 2**31 else f"np.int32({value})"


def _complex_parameter(parameter: dict[str, Any]) -> tuple[str | None, str]:
    """A constant declared complex: ``(value, "")`` or ``(None, reason)``.

    The two-part literal ``(0.0_rk, 1.0_rk)`` is the complex it names, at
    the declared kind -- the token route spelled it as its two parts,
    which Python reads as a tuple (CLUBB's calc_roots multiplied one and
    raised). A real or integer initializer is widened to the complex, as
    Fortran does. Anything richer -- ``cmplx(...)``, arithmetic -- is
    refused with the reason rather than folded by a renderer that has no
    complex arithmetic rules.
    """
    ctor = "np.complex64" if parameter.get("dtype") == "complex64" else "np.complex128"
    kind, payload = parameter["kind"], parameter["payload"]
    if kind in ("real", "real32"):
        return f"{ctor}({_real(payload, kind == 'real32')})", ""
    if kind == "int":
        return f"{ctor}({int(payload)})", ""
    if kind == "expr" and len(payload) == 5:
        opens, real_part, comma, imag_part, closes = payload
        literal = (
            opens == {"t": "op", "v": "("}
            and closes == {"t": "op", "v": ")"}
            and comma == {"t": "op", "v": ","}
            and real_part["t"] in ("real", "real32", "int")
            and imag_part["t"] in ("real", "real32", "int")
        )
        if literal:
            return f"{ctor}(complex({_expression([real_part])}, {_expression([imag_part])}))", ""
    return None, "a complex constant that is not a two-part literal: not spelled by this renderer"


def _module_parameter(parameter: dict[str, Any], source: str) -> str:
    name = parameter["name"].upper()
    kind, payload = parameter["kind"], parameter["payload"]
    where = f"# {source}:{parameter['line']} ({parameter['base_type']})"
    if str(parameter.get("dtype") or "").startswith("complex") and kind != "ref":
        value, why = _complex_parameter(parameter)
        if value is None:
            return f"# SKIPPED {name} = {parameter['init_expr']}  ({why}) {where}"
        return f"{name} = {value}  {where}"
    if kind == "array":
        return f"{name} = {_array(payload)}  {where} [array param]"
    if kind == "int64":
        return f"{name} = np.int64({payload})  {where}"
    if kind == "int":
        return f"{name} = {np_int_literal(int(payload))}  {where}"
    if kind in ("real", "real32"):
        spelled = _stored(_real(payload, kind == "real32"), parameter)
        note = " [unsuffixed default REAL]" if kind == "real32" else ""
        return f"{name} = {spelled}  {where}{note}"
    if kind == "logical":
        return f"{name} = {'True' if payload else 'False'}  {where}"
    if kind == "str":
        return f"{name} = {payload!r}  {where}"
    if kind == "ref":
        return f"{name} = {_stored(payload.upper(), parameter)}  {where}"
    if kind == "expr":
        quotient = _integer_quotient(payload, parameter)
        if quotient is not None and quotient[0] is None:
            return f"# SKIPPED {name} = {parameter['init_expr']}  ({quotient[1]}) {where}"
        if quotient is not None:
            return f"{name} = {quotient[0]}  {where}"
        return f"{name} = {_stored(_typed_expression(payload), parameter)}  {where}"
    return f"# SKIPPED {name} = {parameter['init_expr']}  ({payload}) {where}"


def _local_parameter(parameter: dict[str, Any]) -> str:
    constant = parameter["const"]
    kind, payload = parameter["kind"], parameter["payload"]
    about = f"# local param {parameter['name']} in {parameter['subprogram']}"
    if kind == "array":
        return (
            f"{constant} = {_array(payload, bare=True)}"
            f"  # local param array {parameter['name']} in {parameter['subprogram']}"
        )
    if kind == "int":
        return f"{constant} = {np_int_literal(int(payload))}  {about}"
    if kind in ("real", "real32"):
        spelled = _stored(_real(payload, kind == "real32"), parameter)
        note = " [unsuffixed default REAL]" if kind == "real32" else ""
        return f"{constant} = {spelled}  {about}{note}"
    if kind == "logical":
        return f"{constant} = {'True' if payload else 'False'}  {about}"
    if kind == "str":
        return f"{constant} = {payload!r}  {about}"
    if kind in ("ref", "expr"):
        value = _stored(payload.upper() if kind == "ref" else _typed_expression(payload), parameter)
        # The F77 PARAMETER-statement form historically emitted these bare;
        # the declaration form carries its comment. Kept apart because the
        # emitted files are diffed byte-for-byte against the pipeline's.
        if parameter.get("form") == "parameter_stmt":
            return f"{constant} = {value}"
        return f"{constant} = {value}  {about}"
    return f"# SKIPPED local {constant} = {parameter['init_expr']} ({payload})"


def _hoisted(name: str, entry: dict[str, Any]) -> str:
    value = entry["value"]
    if entry["is_real"]:
        spelled = _real(value, name.startswith("F32_"))
    else:
        # Python 3 forbids a leading zero on a decimal literal.
        if LEADING_ZERO.match(value):
            value = str(int(value))
        spelled = np_int_literal(int(value))
    where = "; ".join(sorted(set(entry["locations"])))
    return f"{name} = {spelled}  # {where}"


def _array(payload: str, *, bare: bool = False) -> str:
    """A literal array constructor. Character elements need ``dtype=object``:
    NumPy would otherwise pick a fixed-width string dtype off the longest
    element, and a later assignment of a longer name would be truncated."""
    dtype = ", dtype=object" if "'" in payload else ""
    if bare:
        return f"np.array({payload}{dtype})"
    inner = re.sub(r"\[", "np.array([", payload, count=1)
    return inner.replace("]", f"]{dtype})", 1)


def _real(value: str, default_kind: bool) -> str:
    """A real constant, at the precision the compiler evaluated it in.

    A literal in Fortran's default real kind is single precision, and the
    value the program sees is that single, promoted -- ``0.1`` is
    0.10000000149011612 where ``0.1_r8`` is 0.1. Writing the decimal text
    into a float64 would give the second for both.
    """
    if default_kind:
        return f"np.float64(np.float32('{value}'))"
    return f"np.float64('{value}')"


INTRINSIC_SPELLING = {
    "abs": "np.abs",
    "acos": "np.arccos",
    "asin": "np.arcsin",
    "atan": "np.arctan",
    "atan2": "np.arctan2",
    "cos": "np.cos",
    "dble": "np.float64",
    "exp": "np.exp",
    "float": "np.float64",
    "int": "int",
    "log": "np.log",
    "log10": "np.log10",
    "max": "max",
    "min": "min",
    "mod": "np.fmod",
    "modulo": "np.mod",
    "real": "np.float64",
    "sin": "np.sin",
    "sqrt": "np.sqrt",
    "tan": "np.tan",
}
"""Intrinsic -> how this target spells it in a constant expression.

``mod`` is ``np.fmod``, the remainder with the dividend's sign that
Fortran's MOD is (F2018 16.9, MOD); ``modulo`` is ``np.mod``, the floored
one. Both were ``np.mod``, so ``mod(-7, 3)`` was 2 where gfortran folds -1
(FNP-D0025). ``nint`` and ``sign`` are not here: neither has a NumPy
function that means it, and ``_call`` spells them."""

INQUIRY_SPELLING = {
    "digits": "53",
    "epsilon": "np.finfo(np.float64).eps",
    "huge": "np.finfo(np.float64).max",
    "radix": "2",
    "tiny": "np.finfo(np.float64).tiny",
}
"""Type inquiries: the argument only says which type is being asked about.
Spelled for a double here, and by ``_inquiry`` for the kind the classifier
recorded as asked about."""

DIGITS = {"float32": "24", "float64": "53", "int32": "31", "int64": "63"}
"""DIGITS per kind: a real's mantissa bits, an integer's magnitude bits."""


def _expression(tokens: list[dict[str, Any]]) -> str:
    """A constant expression over earlier parameters, re-spelled token-wise.

    The target evaluates the same float64 arithmetic the Fortran compiler
    folded, rather than this stage folding it at a different precision.
    """
    spelled = []
    for token in tokens:
        if token["t"] == "ref":
            spelled.append(token["v"].upper())
        elif token["t"] in ("real", "real32"):
            spelled.append(_real(token["v"], token["t"] == "real32"))
        elif token["t"] == "call":
            spelled.append(_call(token))
        elif token["t"] == "array":
            inner = ", ".join(_expression(element) for element in token["elements"])
            spelled.append(f"np.array([{inner}])")
        elif token["t"] == "index":
            subscripts = ", ".join(f"{_expression(argument)} - 1" for argument in token["args"])
            spelled.append(f"{token['v'].upper()}[{subscripts}]")
        elif token["t"] == "spelled":
            # Already target text -- an array constructor the classifier
            # rendered whole, because its elements are not an expression this
            # walk could re-spell one token at a time.
            spelled.append(token["v"])
        else:  # int literals and operators pass through
            spelled.append(token["v"])
    return " ".join(spelled)


def _typed_expression(tokens: list[dict[str, Any]]) -> str:
    """``_expression``, with Fortran's integer arithmetic where the operands
    are integers.

    The token route passes every operator through, and two of them mean
    something else in Python over two integers. ``/`` truncates in Fortran,
    so ``1.0_r8 * (7/2)`` is 3.0 and was emitted as 3.5 (FNP-D0023); ``**``
    of a negative exponent is an integer there too, so ``2 ** (-1)`` is 0
    and was 0.5 (FNP-D0024). The rendered text is parsed and typed -- an
    integer literal, a reference to a constant declared INTEGER, ``int(...)``
    and arithmetic over those are integers; a real literal or reference, a
    conversion or a real-valued call is real; a name of unknown kind is
    neither -- and only a quotient or power whose operands are *both* known
    integers is respelled, as the helpers ``_with_helpers`` defines. An
    expression with neither is returned exactly as ``_expression`` spells
    it, so no constant that was right changes its text.
    """
    text = _expression(tokens)
    if "/" not in text and "**" not in text:
        return text
    try:
        tree = ast.parse(text, mode="eval")
    except SyntaxError:
        return text
    marker = _IntegerArithmetic(_token_types(tokens))
    body = marker.visit(tree.body)
    return ast.unparse(body) if marker.changed else text


def _token_types(tokens: list[dict[str, Any]]) -> dict[str, str | None]:
    """Upper-case name -> ``"int"`` / ``"real"`` / ``None``, for every constant
    the tokens refer to, from the declared dtype the classifier recorded."""
    types: dict[str, str | None] = {}
    for token in tokens:
        if token["t"] in ("ref", "index"):
            dtype = str(token.get("dtype") or "")
            real = dtype.startswith(("float", "complex"))
            types[token["v"].upper()] = "int" if dtype == "int" else "real" if real else None
        for nested in (*token.get("args", ()), *token.get("elements", ())):
            types.update(_token_types(nested))
    return types


_INTEGER_CALLS = frozenset({"int", "np.int32", "np.int64", PYTHON_QUOTIENT, PYTHON_POWER})
_PROMOTING_CALLS = frozenset({"max", "min", "abs", "np.abs", "np.sign", "np.mod", "np.fmod"})


class _IntegerArithmetic(ast.NodeTransformer):
    """Respell ``/`` and ``**`` between two integer operands as Fortran's
    integer division and integer power; see ``_typed_expression``."""

    def __init__(self, types: dict[str, str | None]) -> None:
        self.types = types
        self.changed = False

    def kind(self, node: ast.AST) -> str | None:
        if isinstance(node, ast.Constant):
            if isinstance(node.value, bool) or not isinstance(node.value, int | float):
                return None
            return "int" if isinstance(node.value, int) else "real"
        if isinstance(node, ast.Name):
            return self.types.get(node.id)
        if isinstance(node, ast.Subscript):
            return self.kind(node.value)
        if isinstance(node, ast.UnaryOp):
            return self.kind(node.operand)
        if isinstance(node, ast.BinOp):
            return _promote(self.kind(node.left), self.kind(node.right))
        if isinstance(node, ast.IfExp):
            return _promote(self.kind(node.body), self.kind(node.orelse))
        if isinstance(node, ast.Attribute):
            # ``np.finfo(np.float64).max`` and the like: a real kind's
            # constant; ``np.iinfo(np.int32).max`` an integer kind's, which
            # ``huge(0)`` is spelled as -- read as unknown, ``huge(0)/2`` in a
            # REAL constant stayed Python's true division, 1073741823.5.
            spelled = ast.unparse(node)
            return "real" if "finfo" in spelled else "int" if "iinfo" in spelled else None
        if isinstance(node, ast.Call):
            function = ast.unparse(node.func)
            if function in _INTEGER_CALLS:
                return "int"
            if function in _PROMOTING_CALLS:
                kinds = [self.kind(a) for a in node.args]
                return _promote(*kinds) if kinds else None
            if function.startswith("np.") and function != "np.array":
                return "real"  # a conversion to a real kind, or a real function
        return None

    def visit_BinOp(self, node: ast.BinOp) -> ast.AST:
        self.generic_visit(node)
        if self.kind(node.left) != "int" or self.kind(node.right) != "int":
            return node
        if isinstance(node.op, ast.Div):
            helper = PYTHON_QUOTIENT
        elif isinstance(node.op, ast.Pow) and _signed_exponent(node.right):
            helper = PYTHON_POWER
        else:
            return node
        self.changed = True
        return ast.Call(
            func=ast.Name(id=helper, ctx=ast.Load()), args=[node.left, node.right], keywords=[]
        )


def _integer_valued(tokens: list[dict[str, Any]]) -> bool:
    """Whether an argument's tokens are integer-valued, by the same typing."""
    try:
        tree = ast.parse(_expression(tokens), mode="eval")
    except SyntaxError:
        return False
    return _IntegerArithmetic(_token_types(tokens)).kind(tree.body) == "int"


def _promote(*kinds: str | None) -> str | None:
    """Fortran's promotion, over what ``_IntegerArithmetic.kind`` knows."""
    if "real" in kinds:
        return "real"
    if kinds and all(k == "int" for k in kinds):
        return "int"
    return None


def _signed_exponent(node: ast.AST) -> bool:
    """Whether an exponent may be negative: anything but a literal integer
    of its own sign -- the ``**`` it always was is exact there."""
    return not (isinstance(node, ast.Constant) and isinstance(node.value, int) and node.value >= 0)


def _integer_quotient(
    tokens: list[dict[str, Any]], parameter: dict[str, Any]
) -> tuple[str | None, str] | None:
    """An integer constant with a ``/`` in it: Fortran truncates, the
    token route spelled Python's real division (``HBS = FBS / 2`` is 1.5
    where the compiler has 1; ledger #32 row 18). The one shape this flat
    token list can spell exactly is a single quotient of two integer
    operands, ``int(_f_int_div(A, B))``: truncation toward zero, exact for
    every integer, and the Python ``int`` it always was. It was
    ``int(A / B)``, which divides in binary64 -- ``k8 / 1_i8`` with ``k8 =
    2**53 + 1`` came out 2**53, where the same quotient inside a REAL
    constant already went through ``_f_int_div``. Anything richer is refused
    with the reason rather than folded wrong. ``None`` when the expression
    is not an integer quotient at all."""
    declared = str(parameter.get("dtype") or parameter.get("base_type") or "").lower()
    if not declared.startswith("int"):
        return None
    if not any(t["t"] == "op" and t["v"] == "/" for t in tokens):
        return None
    operands = (tokens[0], tokens[-1])
    plain = all(
        t["t"] in ("int", "ref", "index") and t.get("dtype", "int") == "int" for t in operands
    )
    if len(tokens) == 3 and tokens[1] == {"t": "op", "v": "/"} and plain:
        numerator, denominator = _expression(tokens[:1]), _expression(tokens[2:])
        return f"int({PYTHON_QUOTIENT}({numerator}, {denominator}))", ""
    return None, "integer division inside a larger expression: not spelled by this renderer"


def _call(token: dict[str, Any]) -> str:
    name = token["v"]
    dtype = token.get("dtype")
    if name in INQUIRY_SPELLING:
        return _inquiry(name, token.get("asked") or dtype)
    arguments = ", ".join(_expression(argument) for argument in token["args"])
    if name == "nint":
        return _nint(_expression(token["args"][0]), token.get("kind") or "int32")
    if name == "sign":
        return _sign(token["args"])
    if name in ("real", "float", "dble") and dtype == "float32":
        # ``real(x)`` is the default real: single, then widened by whatever
        # arithmetic it meets -- exact, where ``np.float64(x)`` was not.
        return f"np.float32({arguments})"
    return f"{INTRINSIC_SPELLING.get(name, name)}({arguments})"


def _inquiry(name: str, asked: str | None) -> str:
    """An inquiry, of the kind the argument had, which the classifier
    settled; the 64-bit spelling stands for a record made without kinds.

    An integer kind is a question about an integer: ``huge(0)`` is
    ``np.iinfo(np.int32).max`` and ``digits(0)`` 31, where both were the
    double's answers (FNP-D0026, FNP-D0046); ``digits`` of a single is 24,
    where it was 53 too.
    """
    if name == "digits" and asked in DIGITS:
        return DIGITS[asked]
    if name == "huge" and asked in ("int32", "int64"):
        return f"np.iinfo(np.{asked}).max"
    if asked == "float32":
        return INQUIRY_SPELLING[name].replace("np.float64", "np.float32")
    return INQUIRY_SPELLING[name]


def _nint(x: str, kind: str) -> str:
    """Fortran NINT, as an integer of ``kind``: the nearest integer, a half
    away from zero (F2018 16.9, NINT).

    ``np.rint`` -- what this was -- rounds a half to even and answers a
    float, so ``nint(2.5_r8)`` was 2.0 where gfortran folds 3 (FNP-D0025).
    Nor ``floor(x + 0.5)``: the addition rounds, and 0.49999999999999994
    comes out 1. ``trunc(x)`` and ``x - trunc(x)`` are exact in binary
    floating point, doubling the fraction is exact, and its truncation is
    -1, 0 or 1 exactly as the fraction reaches a half.
    """
    return f"np.{kind}(np.trunc({x}) + np.trunc(2 * (({x}) - np.trunc({x}))))"


def _sign(arguments: list[list[dict[str, Any]]]) -> str:
    """Fortran SIGN(a, b): ``|a|`` with the sign of ``b`` (F2018 16.9, SIGN).

    ``np.sign`` takes one argument and reads a second as the array to write
    into, so ``sign(3.0_r8, -1.0_r8)`` raised when the constants file was
    imported. Over reals it is ``copysign`` -- gfortran gives ``-0.0`` the
    minus sign, as the translated body's ``_f_sign`` does -- and over
    integers a comparison, which keeps the result an integer and makes
    ``b = 0`` positive.
    """
    a, b = (_expression(argument) for argument in arguments)
    if all(_integer_valued(argument) for argument in arguments):
        return f"(abs({a}) if ({b}) >= 0 else -abs({a}))"
    return f"np.copysign(np.abs({a}), {b})"


def _stored(value: str, parameter: dict[str, Any]) -> str:
    """The value as the compiler stores it: a single-precision constant is
    rounded to single before it is widened (``storage == "single"``, or a
    real declared single), and says so beside the value."""
    single = parameter.get("storage") == "single" or (
        parameter.get("dtype") == "float32" and parameter["kind"] in ("real", "ref", "expr")
    )
    if not single or value.startswith("np.float64(np.float32("):
        return value
    inner = value if value.startswith("np.float32(") else f"np.float32({value})"
    return f"np.float64({inner})"


def use_constants_module(resolved: list[dict[str, Any]], module_name: str) -> str:
    """The use-imported constants, from ``use.resolve``'s dependency-ordered
    records. Rendered from the same ``Expr`` trees the oracle's Fortran
    stand-in renders, which is what makes the two sides agree by construction
    rather than by review."""
    lines = [
        '"""Machine-generated by recast — DO NOT EDIT.',
        f"Use-imported constants for module {module_name}; same parsed",
        'expressions as the Fortran stand-in (bit parity by construction)."""',
        "",
        "import numpy as np",
        "",
    ]
    env: dict[str, str | None] = {}
    for entry in resolved:
        value = _python(entry["expr"], env)
        # What the compiler stores: a lone single-precision value is rounded
        # to single before it is widened -- for a single constant as well as
        # a double one initialized from a default-real literal -- and a fold
        # that would be a different number refuses here, by name.
        try:
            storage = fold_check(entry["expr"], entry.get("kind_dtype"))
        except UnsupportedExpression as error:
            raise UnsupportedExpression(f"{entry['name']}: {error}") from error
        if storage == "single":
            single = value if value.startswith("np.float32(") else f"np.float32({value})"
            value = f"np.float64({single})"
        if entry.get("dtype") == "int" and typed(entry["expr"], env) == "real":
            # ``integer, parameter :: isecspday = secspday`` over a real:
            # the assignment converts, truncating toward zero, as ``int`` does.
            value = f"int({value})"
        env[entry["name"]] = entry.get("dtype") or typed(entry["expr"], env)
        where = f"{PurePath(entry['source']).name}:{entry['line']}"
        lines.append(f"{entry['name'].upper()} = {value}  # {where}")
    return "\n".join(_with_helpers(lines, 6)) + "\n"


_HELPERS = {
    name: inspect.getsource(function).replace(f"def {function.__name__}(", f"def {name}(", 1)
    for name, function in ((PYTHON_QUOTIENT, int_div), (PYTHON_POWER, int_pow))
}
"""Fortran's integer division and integer power, as the definitions a
generated constants file carries: ``expr.int_div`` and ``expr.int_pow``
under the names a rendered quotient and power call, read out of the live
functions so the tested helpers and the emitted ones cannot drift apart."""


def _with_helpers(lines: list[str], at: int) -> list[str]:
    """``lines`` with the definition of each helper they call inserted at
    ``at``. The file stands alone -- the translated module's runtime is not
    in it -- so a quotient it spells has to be defined in it; and only where
    one is called, so a file without one is the text it always was."""
    used = [name for name in _HELPERS if any(f"{name}(" in line for line in lines[at:])]
    return [*lines[:at], *(_HELPERS[name] for name in used), *lines[at:]]


def _python(expr: Expr, env: dict[str, str | None] | None = None) -> str:
    if expr.kind == "str":
        return repr(expr.text)  # no arithmetic to fold; a slash in it is text
    # Fortran divides two integers to an integer; ``with_integer_division``
    # marks those quotients from the tree's own types and the declared types
    # of the constants before it, and they truncate toward zero -- ``//``
    # floors, which is a different integer for operands of opposite sign.
    return render(
        with_integer_division(expr, env=env),
        real=lambda text: f"np.float64('{text}')",
        real32=lambda text: f"np.float32('{text}')",
        integer=lambda text: text,
        name=lambda text: text.upper(),
        call=lambda fname, args, kind: python_call(fname, args, result_kind=kind),
        dtype=lambda kind: f"np.{kind}",
        quotient=lambda a, b: f"{PYTHON_QUOTIENT}({a}, {b})",
        power=lambda a, b: f"{PYTHON_POWER}({a}, {b})",
    )
