"""The generated constants modules, rendered from the frontend's records.

Two files every translation ships beside the module it emits. The constants
module carries the zero-literal rule's other half: every parameter and every
hoisted literal, spelled once, with the source location that justifies it --
the generated module reads ``F_273P15`` from here, and this file is the only
place that says what that name means. The use-constants module carries the
constants the source imported from modules that are not being translated,
rendered from the same parsed expressions that the oracle's Fortran stand-in
is built from, so the two sides agree bit-for-bit by construction.

The frontend already classified everything (``constants.extract`` records a
``kind`` and ``payload`` per parameter; ``use.resolve`` returns ``Expr``
trees); this module only decides spelling. A parameter the frontend could not
classify comes out as a ``# SKIPPED`` comment line, not a guess -- the value
of a parameter is a number the Fortran compiler folded, and folding it
differently here is a wrong answer nothing downstream re-checks.
"""

from __future__ import annotations

import re
from pathlib import PurePath, PurePosixPath
from typing import Any

from recast.fortran.expr import Expr, render

__all__ = ["constants_module", "defined_module_parameters", "use_constants_module"]

LEADING_ZERO = re.compile(r"^0\d")


def constants_module(record: dict[str, Any], *, extern: tuple[tuple[str, int], ...] = ()) -> str:
    """The generated constants file for one module, from its constants record.

    ``extern`` names sibling generated constants modules to star-import, as
    ``(stem, how many names it supplies)`` -- the count is documentation for
    whoever reads the generated file, not information the import needs.
    """
    # The file's name, never the path it was found at: an absolute path in a
    # generated file makes the artifact differ between two machines that
    # translated the same source, and ``Candidate.digest()`` with it. The
    # pipeline this reproduces emitted whatever path its command line was
    # given; ``tools/emit_diff.py`` normalizes that away rather than the engine
    # reproducing a reproducibility defect.
    source_name = PurePosixPath(str(record["source_file"])).name
    lines = [
        '"""Machine-generated by recast — DO NOT EDIT."""',
        f"# source: {source_name} (module {record['module']})",
        "",
        "import numpy as np",
        "",
    ]
    for stem, count in extern:
        lines.append(f"from {stem} import *  # noqa: F401,F403 (use-imported params: {count})")
        lines.append("")

    lines.append("# ----- module-level parameters")
    for parameter in record["module_parameters"]:
        lines.append(_module_parameter(parameter, source_name))
    lines.append("")

    lines.append("# ----- subprogram-local parameters")
    for parameter in record["local_parameters"]:
        lines.append(_local_parameter(parameter))
    lines.append("")

    lines.append("# ----- hoisted execution-part literals (zero-literal rule)")
    for name in sorted(record["hoisted_literals"]):
        entry = record["hoisted_literals"][name]
        lines.append(_hoisted(name, entry))
    lines.append("")
    return "\n".join(lines)


def defined_module_parameters(record: dict[str, Any]) -> set[str]:
    """The upper-case names the module's constants file actually defines.

    A sibling module referring to this module's parameter spells it as the
    constants file does when the file has it, and lower-case when the
    frontend could not classify it and the file carries a ``# SKIPPED``
    line instead. Asked of the renderer so the answer cannot disagree with
    the file.
    """
    return {
        parameter["name"].upper()
        for parameter in record["module_parameters"]
        if not _module_parameter(parameter, "").startswith("# SKIPPED")
    }


def _module_parameter(parameter: dict[str, Any], source: str) -> str:
    name = parameter["name"].upper()
    kind, payload = parameter["kind"], parameter["payload"]
    where = f"# {source}:{parameter['line']} ({parameter['base_type']})"
    if kind == "array":
        return f"{name} = {_array(payload)}  {where} [array param]"
    if kind == "int64":
        return f"{name} = np.int64({payload})  {where}"
    if kind == "int":
        return f"{name} = np.int32({int(payload)})  {where}"
    if kind in ("real", "real32"):
        spelled = _real(payload, kind == "real32")
        note = " [unsuffixed default REAL]" if kind == "real32" else ""
        return f"{name} = {spelled}  {where}{note}"
    if kind == "logical":
        return f"{name} = {'True' if payload else 'False'}  {where}"
    if kind == "ref":
        return f"{name} = {payload.upper()}  {where}"
    if kind == "expr":
        return f"{name} = {_expression(payload)}  {where}"
    return f"# SKIPPED {name} = {parameter['init_expr']}  ({payload}) {where}"


def _local_parameter(parameter: dict[str, Any]) -> str:
    constant = parameter["const"]
    kind, payload = parameter["kind"], parameter["payload"]
    about = f"# local param {parameter['name']} in {parameter['subprogram']}"
    if kind == "array":
        return (
            f"{constant} = {_array(payload, bare=True)}"
            f"  # local param array {parameter['name']} in {parameter['subprogram']}"
        )
    if kind == "int":
        return f"{constant} = np.int32({int(payload)})  {about}"
    if kind in ("real", "real32"):
        spelled = _real(payload, kind == "real32")
        note = " [unsuffixed default REAL]" if kind == "real32" else ""
        return f"{constant} = {spelled}  {about}{note}"
    if kind == "logical":
        return f"{constant} = {'True' if payload else 'False'}  {about}"
    if kind in ("ref", "expr"):
        value = payload.upper() if kind == "ref" else _expression(payload)
        # The F77 PARAMETER-statement form historically emitted these bare;
        # the declaration form carries its comment. Kept apart because the
        # emitted files are diffed byte-for-byte against the pipeline's.
        if parameter.get("form") == "parameter_stmt":
            return f"{constant} = {value}"
        return f"{constant} = {value}  {about}"
    return f"# SKIPPED local {constant} = {parameter['init_expr']} ({payload})"


def _hoisted(name: str, entry: dict[str, Any]) -> str:
    value = entry["value"]
    if entry["is_real"]:
        spelled = _real(value, name.startswith("F32_"))
    else:
        # Python 3 forbids a leading zero on a decimal literal.
        if LEADING_ZERO.match(value):
            value = str(int(value))
        spelled = f"np.int32({value})"
    where = "; ".join(sorted(set(entry["locations"])))
    return f"{name} = {spelled}  # {where}"


def _array(payload: str, *, bare: bool = False) -> str:
    """A literal array constructor. Character elements need ``dtype=object``:
    NumPy would otherwise pick a fixed-width string dtype off the longest
    element, and a later assignment of a longer name would be truncated."""
    dtype = ", dtype=object" if "'" in payload else ""
    if bare:
        return f"np.array({payload}{dtype})"
    inner = re.sub(r"\[", "np.array([", payload, count=1)
    return inner.replace("]", f"]{dtype})", 1)


def _real(value: str, default_kind: bool) -> str:
    """A real constant, at the precision the compiler evaluated it in.

    A literal in Fortran's default real kind is single precision, and the
    value the program sees is that single, promoted -- ``0.1`` is
    0.10000000149011612 where ``0.1_r8`` is 0.1. Writing the decimal text
    into a float64 would give the second for both.
    """
    if default_kind:
        return f"np.float64(np.float32('{value}'))"
    return f"np.float64('{value}')"


INTRINSIC_SPELLING = {
    "abs": "np.abs",
    "acos": "np.arccos",
    "asin": "np.arcsin",
    "atan": "np.arctan",
    "atan2": "np.arctan2",
    "cos": "np.cos",
    "dble": "np.float64",
    "exp": "np.exp",
    "float": "np.float64",
    "int": "int",
    "log": "np.log",
    "log10": "np.log10",
    "max": "max",
    "min": "min",
    "mod": "np.mod",
    "modulo": "np.mod",
    "nint": "np.rint",
    "real": "np.float64",
    "sign": "np.sign",
    "sin": "np.sin",
    "sqrt": "np.sqrt",
    "tan": "np.tan",
}
"""Intrinsic -> how this target spells it in a constant expression."""

INQUIRY_SPELLING = {
    "epsilon": "np.finfo(np.float64).eps",
    "huge": "np.finfo(np.float64).max",
    "tiny": "np.finfo(np.float64).tiny",
}
"""Type inquiries: the argument only says which type is being asked about."""


def _expression(tokens: list[dict[str, Any]]) -> str:
    """A constant expression over earlier parameters, re-spelled token-wise.

    The target evaluates the same float64 arithmetic the Fortran compiler
    folded, rather than this stage folding it at a different precision.
    """
    spelled = []
    for token in tokens:
        if token["t"] == "ref":
            spelled.append(token["v"].upper())
        elif token["t"] in ("real", "real32"):
            spelled.append(_real(token["v"], token["t"] == "real32"))
        elif token["t"] == "call":
            spelled.append(_call(token))
        elif token["t"] == "spelled":
            # Already target text -- an array constructor the classifier
            # rendered whole, because its elements are not an expression this
            # walk could re-spell one token at a time.
            spelled.append(token["v"])
        else:  # int literals and operators pass through
            spelled.append(token["v"])
    return " ".join(spelled)


def _call(token: dict[str, Any]) -> str:
    name = token["v"]
    if name in INQUIRY_SPELLING:
        return INQUIRY_SPELLING[name]
    arguments = ", ".join(_expression(argument) for argument in token["args"])
    return f"{INTRINSIC_SPELLING.get(name, name)}({arguments})"


def use_constants_module(resolved: list[dict[str, Any]], module_name: str) -> str:
    """The use-imported constants, from ``use.resolve``'s dependency-ordered
    records. Rendered from the same ``Expr`` trees the oracle's Fortran
    stand-in renders, which is what makes the two sides agree by construction
    rather than by review."""
    lines = [
        '"""Machine-generated by recast — DO NOT EDIT.',
        f"Use-imported constants for module {module_name}; same parsed",
        'expressions as the Fortran stand-in (bit parity by construction)."""',
        "",
        "import numpy as np",
        "",
    ]
    for entry in resolved:
        value = _python(entry["expr"])
        where = f"{PurePath(entry['source']).name}:{entry['line']}"
        lines.append(f"{entry['name'].upper()} = {value}  # {where}")
    return "\n".join(lines) + "\n"


def _python(expr: Expr) -> str:
    return render(
        expr,
        real=lambda text: f"np.float64('{text}')",
        integer=lambda text: text,
        name=lambda text: text.upper(),
    )
